var on =+ prompt("which table do you want to print!")
var table=(on*1)
alert(table)

var table=(on*2)
alert(table)
var table=(on*3)
alert(table)
var table=(on*4)
alert(table)
var table=(on*5)
alert(table)
var table=(on*6)
alert(table)
var table=(on*7)
alert(table)
var table=(on*8)
alert(table)
var table=(on*9)
alert(table)
var table=(on*10)
alert(table)